tab_spaces = 4
max_width = 100
reorder_imports = true

# unstable
unstable_features = true
group_imports = "Preserve"
imports_granularity = "Crate"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
comment_width = 100
wrap_comments = true
